swagger: '2.0'
info :
  title : Bank Argent API documentation 
  description : Contains all available API endpoints in this codebase
  termsOfService: 'http://swagger.io/terms/'
  version : 1.1.0
 
host: localhost:3001
basePath: /api/v1
schemes:
  - http
  
paths :
 /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
           $ref: '#/definitions/Login'

      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  
 /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'

      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
 
 /user/profile:
    post:
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type : string
          # schema:
          #   type : string

      responses:
        '200':
          description: User profile retrieved successully
          # content:
          #   "application/json":
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          # schema:
          type : string
            
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'

      responses:
        '200':
          description: User profile retrieved successully
          # content:
          #   "application/json":
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

# Visualiser toutes les transactions pour le mois en cours
 /user/transaction :
    get:
      tags: 
        - User Module
      description: API for fetching user transactions for current month
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
        # schema:
        type : string
        
      responses:
        '200':
          description: "user accounts recieved successully"
          # content:
          #   "application/json":
          schema: 
            $ref: '#/definitions/AccountList'
        '400':
          description: "Invalid fields"
        '500':
          description: "Internal Server Error" 
          
#Visualiser le détail d'une transaction dans une vue particulière
 /user/transaction/{transactionID} :   
    get:
      tags: 
        - User Module
      description: API for fetching transaction detail
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
        # schema:
        type : string
          
      - in: path
        name: transactionID
        description: User's account ID
        required: true
        # schema:
        type : integer
        
      responses:
        '200':
          description: "transaction accounts recieved successully"
          # content:
          #   "application/json":
          schema: 
            $ref: '#/definitions/TransactionsList'
        '400':
          description: "Invalid fields"
        '500':
          description: "Internal Server Error"       
  
#Modifier la catégorie d'une transaction
 /user/transaction/{transactionID}/category :   
    patch:
      tags: 
        - User Module
      description:  API for updating a transaction's category
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
        # schema:
        type : string
          
      - in: path
        name: transactionID
        description: User's account ID
        required: true
        # schema:
        type : integer
          
      - in: body
        name: body
        required: true
        description: Update transaction's category
        schema:
          $ref: '#/definitions/TransactionsUpdateCategory'
        
      responses:
        '200':
          description: "transaction details recieved successully"
          # content:
          #   "application/json":
          schema: 
            $ref: '#/definitions/TransactionsList'
        '400':
          description: "Invalid fields"
        '500':
          description: "Internal Server Error"       
   
#Ajouter, modifier et supprimer une note sur une transaction
 /user/transaction/{transactionID}/note :   
    put:
      tags: 
        - User Module
      description:  API for updating a transaction's notes
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
        # schema:
        type : string
          
      - in: path
        name: transactionID
        description: User's account ID
        required: true
        # schema:
        type : integer
          
      - in: body
        name: body
        required: true
        description: Update transaction's notes
        schema:
          $ref: '#/definitions/TransactionsUpdateNotes'
        
      responses:
        '200':
          description: "transaction details recieved successully"
          # content:
          #   "application/json":
          schema: 
            $ref: '#/definitions/TransactionsList'
        '400':
          description: "Invalid fields"
        '500':
          description: "Internal Server Error"       
     
tags :
  - name : User Module
    description: users module group 
    
# components:
#   schemas:
definitions:
    User:
      type: object
      properties:
        email:
          type: string
          description: user email
        password:
          type: string
          description: user password
        firstName:
          type: string
          description: user first name
        lastName:
          type: string
          description: user last name
          
    Login:
      type: object
      properties:
        email:
          type: string
          description: user email
        password:
          type: string
          description: user password
        
    ApiResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          properties:
            id:
              type: string
            email:
              type: string
            
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    
    AccountList:
      type: object
      properties:
        NameOfAccount:
          type: string
        AccountID:
          type: number
        Balance:
          type: integer
        transactions:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
              description:
                type: string
              amount:
                type: number
              balance:
                type: integer
                
    UserProfile:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string      
    
    TransactionsList:
      type: object
      properties:
        transactionID:
          type: integer
          format: int64
        date:
          type: string
        description:
          type: string
        amount:
          type: number
        balance:
          type: string
        type:
          type: string
        category:
          type: string
        notes:
          type: string
    
    TransactionsUpdateCategory:
      type: object
      properties:
        category:
          type: string
          
    TransactionsUpdateNotes:
      type: object
      properties:
        notes:
          type: string